### ISSUE TITLE
Tree structure?

### ISSUE THREAD

**Issue by systemchef** [handsontable/hot-table#1]
Obviously its not an issue, rather a feature request. while this module is under development, is it possible to add tree-grid functionality ?

**Comment by gaurav21r** [comment]
+1 I think this is the **only major** functionality that hands-on-table is missing for an enterprise audience.

**Comment by glinkot** [comment]
Yes, I just sent a contact request to ask about this, but it looks like there is none so I'll have to choose something else.

**Comment by warpech** [comment]
This repository is for `<hot-table>`, which is a custom element wrapper of [Handsontable](https://github.com/handsontable/handsontable). This kind of feature request is relevant in that repo. 

Since you ask, a tree structure it was requested there: https://github.com/handsontable/handsontable/issues/2165,https://github.com/handsontable/handsontable/issues/1924. It is noted on the [Feature requests wiki](https://github.com/handsontable/handsontable/wiki/Feature-requests).

When it is implemented in Handsontable, it will also become available in `<hot-table>`.

Thanks for asking and sorry for late reply!
