### ISSUE TITLE
Context menu does not show up

### ISSUE THREAD

**Issue by warpech** [handsontable/hot-table#51]
## Steps to reproduce

1. Install hot-table locally using bower
2. Run a local server (I use Polyserve)
3. Go to the demo page `index.html`
4. Right-click on any cell

## Expected

A context menu should open because the attribute `context-menu` is present.

## Actual

Context menu does not open but I can see that the vertical scrollbar moves a bit. It seems as if the context menu opens unstyled outside of the browser viewport.

Tested using Chrome.

**Comment by warpech** [comment]
I pushed a fix to a branch. It is a work in progress, I will make a PR when it's ready.

**Comment by icaromro** [comment]
I'm having this problem on version 2.0.0. When right clicking for the context menu I can see that the vertical scroll bar move and when I go to the end of the page the context menu is opened there and I get the following error message: 
`ngHandsontable.js:25 Uncaught TypeError: Cannot set property 'isHotTableEnv' of undefined`

**Comment by warpech** [comment]
My branch that fixes the problem: https://github.com/handsontable/hot-table/tree/upgrade-hot

@handsontable/core pls finish this as a proper PR whenever possible.

**Comment by ketan-navadiya** [comment]
Could anyone please provide any workaround for "ContextMenu" problem? We are using Hansontable Pro version 4.0.0 with the Hot table. I am facing the same issue. 

We really needed the solution because earlier we used a free version of Handsontable and ContextMenu function was working fine. Now, Our Client decided to use Pro version to add an extra feature if we didn't get any workaround or PR then we need to move back to the free version because our lots of functionality depend on "ContextMenu" feature.

**Comment by AMBudnik** [comment]
Hi @ketan-navadiya 

the solution provided by @warpech will be pulled in the next version of Handsontable (PRO and CE).

**Comment by ketan-navadiya** [comment]
Hi @AMBudnik, Thanks for the response.
 When will be this next version release?

**Comment by AMBudnik** [comment]
It is planned for 11th of July.

**Comment by ketan-navadiya** [comment]
@AMBudnik okay, Thanks.

**Comment by budnix** [comment]
Fixed and released in 1.0.0
